import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "zh-TW" | "zh-CN" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "zh-TW",
  setLanguage: () => {},
  t: (key) => key,
});

// ─── Translations ─────────────────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  "zh-TW": {
    // Nav
    "nav.home": "首頁",
    "nav.courses": "課程搜尋",
    "nav.favorites": "收藏課程",
    "nav.choices": "模擬志願",
    "nav.ai": "AI 推薦",
    "nav.compare": "課程比較",
    "nav.admin": "管理後台",
    "nav.login": "登入",
    "nav.logout": "登出",
    "nav.profile": "我的帳戶",

    // Home
    "home.hero.title": "香港升學課程資訊平台",
    "home.hero.subtitle": "全面收錄 JUPAS 課程資訊，助你作出最佳升學選擇",
    "home.hero.cta": "立即搜尋課程",
    "home.hero.cta2": "AI 課程推薦",
    "home.features.search": "智能搜尋",
    "home.features.search.desc": "多維度篩選，快速找到最適合的課程",
    "home.features.compare": "課程比較",
    "home.features.compare.desc": "並排比較多個課程，生成 PDF 報告",
    "home.features.ai": "AI 推薦",
    "home.features.ai.desc": "根據 DSE 成績智能推薦最適合課程",
    "home.features.choices": "志願模擬",
    "home.features.choices.desc": "模擬填寫 20 個 JUPAS 志願",
    "home.stats.courses": "收錄課程",
    "home.stats.institutions": "合作院校",
    "home.stats.users": "用戶使用",
    "home.modules.jupas": "JUPAS 課程",
    "home.modules.eapp": "E-APP 課程",
    "home.modules.eapp.soon": "即將推出",
    "home.modules.mainland": "內地升學",
    "home.modules.mainland.soon": "即將推出",

    // Courses
    "courses.title": "JUPAS 課程搜尋",
    "courses.search.placeholder": "搜尋課程名稱或課程代號...",
    "courses.filter.degreeType": "學位類型",
    "courses.filter.institution": "院校",
    "courses.filter.duration": "修讀年期",
    "courses.filter.qualification": "資歷架構",
    "courses.filter.scoring": "計分方式",
    "courses.filter.interview": "面試安排",
    "courses.filter.scoreGap": "分差",
    "courses.filter.funding": "資助類型",
    "courses.filter.minReq": "最低要求",
    "courses.filter.groupA": "組別A錄取",
    "courses.filter.tuition": "學費範圍",
    "courses.filter.tuition.unit": "元/年",
    "courses.sort.label": "排序方式",
    "courses.sort.quota_desc": "學額：多至少",
    "courses.sort.quota_asc": "學額：少至多",
    "courses.sort.tuition_desc": "學費：多至少",
    "courses.sort.tuition_asc": "學費：少至多",
    "courses.sort.probability_desc": "最可能取錄",
    "courses.sort.probability_asc": "最不可能取錄",
    "courses.sort.groupA_desc": "組別A申請者：多至少",
    "courses.sort.groupA_asc": "組別A申請者：少至多",
    "courses.sort.applicants_desc": "申請者：多至少",
    "courses.sort.applicants_asc": "申請者：少至多",
    "courses.col.code": "課程代號",
    "courses.col.name": "課程名稱",
    "courses.col.institution": "院校",
    "courses.col.quota": "收生人數",
    "courses.col.median": "中位數",
    "courses.col.q1": "下四分位數",
    "courses.col.minReq": "最低要求",
    "courses.col.tuition": "學費",
    "courses.col.duration": "年期",
    "courses.col.scoring": "計分",
    "courses.col.admitted": "取錄人數",
    "courses.col.groupA": "組別A",
    "courses.noResults": "沒有符合條件的課程",
    "courses.loading": "載入中...",
    "courses.total": "共 {count} 個課程",
    "courses.clearFilters": "清除篩選",
    "courses.addToChoices": "加入志願",
    "courses.addToFavorites": "收藏",
    "courses.removeFromFavorites": "取消收藏",
    "courses.addToCompare": "加入比較",
    "courses.viewDetail": "查看詳情",
    "courses.new": "新課程",
    "courses.scoringChanged": "計分改變",
    "courses.groupAOnly": "只錄取組別A",

    // Detail
    "detail.back": "返回課程列表",
    "detail.basicInfo": "基本資料",
    "detail.admissionStats": "收生統計",
    "detail.requirements": "入學要求",
    "detail.description": "課程簡介",
    "detail.careers": "就業前景",
    "detail.requiredSubjects": "必修科目",
    "detail.weightedSubjects": "加成科目",
    "detail.interviewReq": "面試要求",
    "detail.website": "官方網站",
    "detail.notFound": "找不到此課程",

    // Favorites
    "favorites.title": "收藏課程",
    "favorites.empty": "你還未收藏任何課程",
    "favorites.empty.cta": "前往搜尋課程",
    "favorites.loginRequired": "請登入以使用收藏功能",

    // Choices
    "choices.title": "模擬填寫 JUPAS 志願",
    "choices.subtitle": "最多可選擇 20 個志願，拖動調整排序",
    "choices.empty": "尚未加入任何志願",
    "choices.empty.cta": "前往搜尋課程",
    "choices.loginRequired": "請登入以使用志願模擬功能",
    "choices.save": "儲存志願",
    "choices.saved": "志願已儲存",
    "choices.rank": "志願 {rank}",
    "choices.remove": "移除",
    "choices.max": "已達上限（20個志願）",
    "choices.addFromSearch": "從課程搜尋加入",

    // AI
    "ai.title": "AI 課程推薦",
    "ai.subtitle": "輸入你的 DSE 成績，AI 為你推薦最適合的課程",
    "ai.dse.chinese": "中文",
    "ai.dse.english": "英文",
    "ai.dse.math": "數學",
    "ai.dse.ls": "通識/公民與社會發展科",
    "ai.dse.elective1": "選修科目 1",
    "ai.dse.elective2": "選修科目 2",
    "ai.dse.elective3": "選修科目 3",
    "ai.dse.electiveName": "科目名稱",
    "ai.dse.score": "成績",
    "ai.interests": "興趣領域",
    "ai.interests.placeholder": "例如：科技、商業、醫療...",
    "ai.targetInstitutions": "目標院校（可選）",
    "ai.submit": "獲取 AI 推薦",
    "ai.loading": "AI 分析中...",
    "ai.result.title": "AI 推薦結果",
    "ai.loginRequired": "請登入以使用 AI 推薦功能",
    "ai.grades": "DSE 成績",
    "ai.addSubject": "加入科目",
    "ai.selectSubject": "選擇科目",
    "ai.generate": "獲取 AI 推薦",
    "ai.result": "AI 推薦結果",
    "ai.result.empty": "填寫成績後，AI 將為你生成個人化推薦",
    "ai.analyzing": "AI 分析中，請稍候...",
    "ai.browseCourses": "瀏覽相關課程",
    "ai.preferences": "其他偏好（可選）",
    "ai.preferences.placeholder": "例如：希望在港島區就讀、不想讀太多數學...",
    "ai.targetInstitutions.placeholder": "例如：香港大學、香港中文大學",

    // Compare
    "compare.title": "課程比較",
    "compare.subtitle": "選擇 2-6 個課程進行比較",
    "compare.empty": "尚未選擇任何課程",
    "compare.generate": "生成比較報告",
    "compare.generatePDF": "下載 PDF 報告",
    "compare.saving": "生成中...",
    "compare.loginRequired": "請登入以儲存報告",
    "compare.analysis": "AI 分析",
    "compare.analyze": "AI 深度分析",
    "compare.aiAnalysis": "AI 比较分析",
    "compare.aiAnalysis.empty": "點擊「AI 深度分析」按鈕，獲取各課程的深入比較分析",

    // Admin
    "admin.title": "管理後台",
    "admin.courses": "課程管理",
    "admin.addCourse": "新增課程",
    "admin.editCourse": "編輯課程",
    "admin.deleteCourse": "刪除課程",
    "admin.bulkImport": "批量匯入",
    "admin.save": "儲存",
    "admin.cancel": "取消",
    "admin.confirm.delete": "確認刪除此課程？",
    "admin.import.instructions": "請上傳 JSON 格式的課程資料",
    "admin.import.success": "成功匯入 {count} 個課程",

    // Qualification
    "qual.bachelor": "學士學位",
    "qual.higher_diploma": "高級文憑",
    "qual.associate_degree": "副學士",

    // Funding
    "funding.ugc": "教資會",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
     "funding.self_financed": "自資",
    // Interview
    "interview.required": "必須面試",
    "interview.not_required": "無需面試",
    "interview.by_invitation": "獲邀面試",
    "interview.portfolio": "作品集面試",
    // Score gap
    "scoreGap.above_median": "高於中位數",
    "scoreGap.above_q1": "高於下四分位數",
    "scoreGap.below_q1": "低於下四分位數",
    "scoreGap.between_median_q1": "介乎中位數與下四分位數",

    // Duration
    "duration.years": "{n} 年",

    // Common
    "common.all": "全部",
    "common.yes": "是",
    "common.no": "否",
    "common.unknown": "未知",
    "common.hkd": "港幣",
    "common.perYear": "/年",
    "common.loading": "載入中...",
    "common.error": "發生錯誤",
    "common.retry": "重試",
    "common.close": "關閉",
    "common.confirm": "確認",
    "common.cancel": "取消",
    "common.save": "儲存",
    "common.edit": "編輯",
    "common.delete": "刪除",
    "common.search": "搜尋",
    "common.filter": "篩選",
    "common.sort": "排序",
    "common.reset": "重設",
    "common.submit": "提交",
    "common.loginRequired": "請先登入",
    "common.comingSoon": "即將推出",
    "common.page": "第 {page} 頁",
    "common.of": "共",
    "common.results": "個結果",
    "common.noData": "暫無資料",
    "common.points": "分",

    // Footer
    "footer.disclaimer": "本平台為第三方資訊平台，所有資料僅供參考，請以各院校官方公佈為準。",
    "footer.copyright": "© 2025 JupaSearch. 版權所有。",
  },

  "zh-CN": {
    "nav.home": "首页",
    "nav.courses": "课程搜索",
    "nav.favorites": "收藏课程",
    "nav.choices": "模拟志愿",
    "nav.ai": "AI 推荐",
    "nav.compare": "课程比较",
    "nav.admin": "管理后台",
    "nav.login": "登录",
    "nav.logout": "登出",
    "nav.profile": "我的账户",
    "home.hero.title": "香港升学课程信息平台",
    "home.hero.subtitle": "全面收录 JUPAS 课程信息，助你作出最佳升学选择",
    "home.hero.cta": "立即搜索课程",
    "home.hero.cta2": "AI 课程推荐",
    "home.features.search": "智能搜索",
    "home.features.search.desc": "多维度筛选，快速找到最适合的课程",
    "home.features.compare": "课程比较",
    "home.features.compare.desc": "并排比较多个课程，生成 PDF 报告",
    "home.features.ai": "AI 推荐",
    "home.features.ai.desc": "根据 DSE 成绩智能推荐最适合课程",
    "home.features.choices": "志愿模拟",
    "home.features.choices.desc": "模拟填写 20 个 JUPAS 志愿",
    "home.stats.courses": "收录课程",
    "home.stats.institutions": "合作院校",
    "home.stats.users": "用户使用",
    "home.modules.jupas": "JUPAS 课程",
    "home.modules.eapp": "E-APP 课程",
    "home.modules.eapp.soon": "即将推出",
    "home.modules.mainland": "内地升学",
    "home.modules.mainland.soon": "即将推出",
    "courses.title": "JUPAS 课程搜索",
    "courses.search.placeholder": "搜索课程名称或课程代号...",
    "courses.filter.degreeType": "学位类型",
    "courses.filter.institution": "院校",
    "courses.filter.duration": "修读年期",
    "courses.filter.qualification": "资历架构",
    "courses.filter.scoring": "计分方式",
    "courses.filter.interview": "面试安排",
    "courses.filter.scoreGap": "分差",
    "courses.filter.funding": "资助类型",
    "courses.filter.minReq": "最低要求",
    "courses.filter.groupA": "组别A录取",
    "courses.filter.tuition": "学费范围",
    "courses.filter.tuition.unit": "元/年",
    "courses.sort.label": "排序方式",
    "courses.sort.quota_desc": "学额：多至少",
    "courses.sort.quota_asc": "学额：少至多",
    "courses.sort.tuition_desc": "学费：多至少",
    "courses.sort.tuition_asc": "学费：少至多",
    "courses.sort.probability_desc": "最可能录取",
    "courses.sort.probability_asc": "最不可能录取",
    "courses.sort.groupA_desc": "组别A申请者：多至少",
    "courses.sort.groupA_asc": "组别A申请者：少至多",
    "courses.sort.applicants_desc": "申请者：多至少",
    "courses.sort.applicants_asc": "申请者：少至多",
    "courses.col.code": "课程代号",
    "courses.col.name": "课程名称",
    "courses.col.institution": "院校",
    "courses.col.quota": "收生人数",
    "courses.col.median": "中位数",
    "courses.col.q1": "下四分位数",
    "courses.col.minReq": "最低要求",
    "courses.col.tuition": "学费",
    "courses.col.duration": "年期",
    "courses.col.scoring": "计分",
    "courses.col.admitted": "录取人数",
    "courses.col.groupA": "组别A",
    "courses.noResults": "没有符合条件的课程",
    "courses.loading": "加载中...",
    "courses.total": "共 {count} 个课程",
    "courses.clearFilters": "清除筛选",
    "courses.addToChoices": "加入志愿",
    "courses.addToFavorites": "收藏",
    "courses.removeFromFavorites": "取消收藏",
    "courses.addToCompare": "加入比较",
    "courses.viewDetail": "查看详情",
    "courses.new": "新课程",
    "courses.scoringChanged": "计分改变",
    "courses.groupAOnly": "只录取组别A",
    "detail.back": "返回课程列表",
    "detail.basicInfo": "基本资料",
    "detail.admissionStats": "收生统计",
    "detail.requirements": "入学要求",
    "detail.description": "课程简介",
    "detail.careers": "就业前景",
    "detail.requiredSubjects": "必修科目",
    "detail.weightedSubjects": "加成科目",
    "detail.interviewReq": "面试要求",
    "detail.website": "官方网站",
    "detail.notFound": "找不到此课程",
    "favorites.title": "收藏课程",
    "favorites.empty": "你还未收藏任何课程",
    "favorites.empty.cta": "前往搜索课程",
    "favorites.loginRequired": "请登录以使用收藏功能",
    "choices.title": "模拟填写 JUPAS 志愿",
    "choices.subtitle": "最多可选择 20 个志愿，拖动调整排序",
    "choices.empty": "尚未加入任何志愿",
    "choices.empty.cta": "前往搜索课程",
    "choices.loginRequired": "请登录以使用志愿模拟功能",
    "choices.save": "保存志愿",
    "choices.saved": "志愿已保存",
    "choices.rank": "志愿 {rank}",
    "choices.remove": "移除",
    "choices.max": "已达上限（20个志愿）",
    "choices.addFromSearch": "从课程搜索加入",
    "ai.title": "AI 课程推荐",
    "ai.subtitle": "输入你的 DSE 成绩，AI 为你推荐最适合的课程",
    "ai.dse.chinese": "中文",
    "ai.dse.english": "英文",
    "ai.dse.math": "数学",
    "ai.dse.ls": "通识/公民与社会发展科",
    "ai.dse.elective1": "选修科目 1",
    "ai.dse.elective2": "选修科目 2",
    "ai.dse.elective3": "选修科目 3",
    "ai.dse.electiveName": "科目名称",
    "ai.dse.score": "成绩",
    "ai.interests": "兴趣领域",
    "ai.interests.placeholder": "例如：科技、商业、医疗...",
    "ai.targetInstitutions": "目标院校（可选）",
    "ai.submit": "获取 AI 推荐",
    "ai.loading": "AI 分析中...",
    "ai.result.title": "AI 推荐结果",    "ai.loginRequired": "请登录以使用 AI 推荐功能",
    "ai.grades": "DSE 成绩",
    "ai.addSubject": "加入科目",
    "ai.selectSubject": "选择科目",
    "ai.generate": "获取 AI 推荐",
    "ai.result": "AI 推荐结果",
    "ai.result.empty": "填写成绩后，AI 将为你生成个性化推荐",
    "ai.analyzing": "AI 分析中，请稍候...",
    "ai.browseCourses": "浏览相关课程",
    "ai.preferences": "其他偏好（可选）",
    "ai.preferences.placeholder": "例如：希望在港岛区就读、不想读太多数学...",
    "ai.targetInstitutions.placeholder": "例如：香港大学、香港中文大学",

    // Compare
    "compare.title": "课程比较",
    "compare.subtitle": "选择 2-6 个课程进行比较",
    "compare.empty": "尚未选择任何课程",
    "compare.generate": "生成比较报告",
    "compare.generatePDF": "下载 PDF 报告",
    "compare.saving": "生成中...",
    "compare.loginRequired": "请登录以保存报告",
    "compare.analysis": "AI 分析",
    "compare.analyze": "AI 深度分析",
    "compare.aiAnalysis": "AI 比较分析",
    "compare.aiAnalysis.empty": "点击「AI 深度分析」按钮，获取各课程的深入比较分析",
    "admin.title": "管理后台",
    "admin.courses": "课程管理",
    "admin.addCourse": "新增课程",
    "admin.editCourse": "编辑课程",
    "admin.deleteCourse": "删除课程",
    "admin.bulkImport": "批量导入",
    "admin.save": "保存",
    "admin.cancel": "取消",
    "admin.confirm.delete": "确认删除此课程？",
    "admin.import.instructions": "请上传 JSON 格式的课程资料",
    "admin.import.success": "成功导入 {count} 个课程",
    "qual.bachelor": "学士学位",
    "qual.higher_diploma": "高级文凭",
    "qual.associate_degree": "副学士",
    "funding.ugc": "教资会",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
    "funding.self_financed": "自资",
    // Interview
    "interview.required": "必须面试",
    "interview.not_required": "无需面试",
    "interview.by_invitation": "获邀面试",
    "interview.portfolio": "作品集面试",
    "scoreGap.above_median": "高于中位数",
    "scoreGap.above_q1": "高于下四分位数",
    "scoreGap.below_q1": "低于下四分位数",
    "scoreGap.between_median_q1": "介于中位数与下四分位数",
    "duration.years": "{n} 年",
    "common.all": "全部",
    "common.yes": "是",
    "common.no": "否",
    "common.unknown": "未知",
    "common.hkd": "港币",
    "common.perYear": "/年",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.retry": "重试",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.reset": "重设",
    "common.submit": "提交",
    "common.loginRequired": "请先登录",
    "common.comingSoon": "即将推出",
    "common.page": "第 {page} 页",
    "common.of": "共",
    "common.results": "个结果",
    "common.noData": "暂无资料",
    "common.points": "分",
    "footer.disclaimer": "本平台为第三方信息平台，所有资料仅供参考，请以各院校官方公布为准。",
    "footer.copyright": "© 2025 JupaSearch. 版权所有。",
  },

  en: {
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.favorites": "Favourites",
    "nav.choices": "My Choices",
    "nav.ai": "AI Advisor",
    "nav.compare": "Compare",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.profile": "My Account",
    "home.hero.title": "Hong Kong University Admissions Platform",
    "home.hero.subtitle": "Comprehensive JUPAS course information to help you make the best choice",
    "home.hero.cta": "Search Courses",
    "home.hero.cta2": "AI Recommendations",
    "home.features.search": "Smart Search",
    "home.features.search.desc": "Multi-dimensional filters to find the perfect course",
    "home.features.compare": "Course Comparison",
    "home.features.compare.desc": "Compare courses side by side and generate PDF reports",
    "home.features.ai": "AI Advisor",
    "home.features.ai.desc": "Intelligent course recommendations based on DSE results",
    "home.features.choices": "Choice Simulation",
    "home.features.choices.desc": "Simulate filling in 20 JUPAS choices",
    "home.stats.courses": "Courses Listed",
    "home.stats.institutions": "Institutions",
    "home.stats.users": "Users",
    "home.modules.jupas": "JUPAS Courses",
    "home.modules.eapp": "E-APP Courses",
    "home.modules.eapp.soon": "Coming Soon",
    "home.modules.mainland": "Mainland Studies",
    "home.modules.mainland.soon": "Coming Soon",
    "courses.title": "JUPAS Course Search",
    "courses.search.placeholder": "Search by course name or code...",
    "courses.filter.degreeType": "Degree Type",
    "courses.filter.institution": "Institution",
    "courses.filter.duration": "Duration",
    "courses.filter.qualification": "Qualification",
    "courses.filter.scoring": "Scoring Method",
    "courses.filter.interview": "Interview",
    "courses.filter.scoreGap": "Score Gap",
    "courses.filter.funding": "Funding Type",
    "courses.filter.minReq": "Min. Requirement",
    "courses.filter.groupA": "Group A Only",
    "courses.filter.tuition": "Tuition Range",
    "courses.filter.tuition.unit": "HKD/yr",
    "courses.sort.label": "Sort By",
    "courses.sort.quota_desc": "Quota: High to Low",
    "courses.sort.quota_asc": "Quota: Low to High",
    "courses.sort.tuition_desc": "Tuition: High to Low",
    "courses.sort.tuition_asc": "Tuition: Low to High",
    "courses.sort.probability_desc": "Most Likely to Admit",
    "courses.sort.probability_asc": "Least Likely to Admit",
    "courses.sort.groupA_desc": "Group A Applicants: High to Low",
    "courses.sort.groupA_asc": "Group A Applicants: Low to High",
    "courses.sort.applicants_desc": "Applicants: High to Low",
    "courses.sort.applicants_asc": "Applicants: Low to High",
    "courses.col.code": "Code",
    "courses.col.name": "Course Name",
    "courses.col.institution": "Institution",
    "courses.col.quota": "Quota",
    "courses.col.median": "Median",
    "courses.col.q1": "Lower Quartile",
    "courses.col.minReq": "Min. Req.",
    "courses.col.tuition": "Tuition",
    "courses.col.duration": "Duration",
    "courses.col.scoring": "Scoring",
    "courses.col.admitted": "Admitted",
    "courses.col.groupA": "Group A",
    "courses.noResults": "No courses found",
    "courses.loading": "Loading...",
    "courses.total": "{count} courses found",
    "courses.clearFilters": "Clear Filters",
    "courses.addToChoices": "Add to Choices",
    "courses.addToFavorites": "Favourite",
    "courses.removeFromFavorites": "Unfavourite",
    "courses.addToCompare": "Compare",
    "courses.viewDetail": "View Details",
    "courses.new": "New",
    "courses.scoringChanged": "Scoring Changed",
    "courses.groupAOnly": "Group A Only",
    "detail.back": "Back to Course List",
    "detail.basicInfo": "Basic Information",
    "detail.admissionStats": "Admission Statistics",
    "detail.requirements": "Entry Requirements",
    "detail.description": "Course Description",
    "detail.careers": "Career Prospects",
    "detail.requiredSubjects": "Required Subjects",
    "detail.weightedSubjects": "Weighted Subjects",
    "detail.interviewReq": "Interview Requirements",
    "detail.website": "Official Website",
    "detail.notFound": "Course not found",
    "favorites.title": "Favourite Courses",
    "favorites.empty": "You have no favourite courses yet",
    "favorites.empty.cta": "Browse Courses",
    "favorites.loginRequired": "Please login to use favourites",
    "choices.title": "JUPAS Choice Simulation",
    "choices.subtitle": "Select up to 20 choices and drag to reorder",
    "choices.empty": "No choices added yet",
    "choices.empty.cta": "Browse Courses",
    "choices.loginRequired": "Please login to use choice simulation",
    "choices.save": "Save Choices",
    "choices.saved": "Choices saved",
    "choices.rank": "Choice {rank}",
    "choices.remove": "Remove",
    "choices.max": "Maximum 20 choices reached",
    "choices.addFromSearch": "Add from Course Search",
    "ai.title": "AI Course Advisor",
    "ai.subtitle": "Enter your DSE results and get personalised course recommendations",
    "ai.dse.chinese": "Chinese",
    "ai.dse.english": "English",
    "ai.dse.math": "Mathematics",
    "ai.dse.ls": "Liberal Studies / CS&S",
    "ai.dse.elective1": "Elective 1",
    "ai.dse.elective2": "Elective 2",
    "ai.dse.elective3": "Elective 3",
    "ai.dse.electiveName": "Subject Name",
    "ai.dse.score": "Grade",
    "ai.interests": "Areas of Interest",
    "ai.interests.placeholder": "e.g. Technology, Business, Medicine...",
    "ai.targetInstitutions": "Target Institutions (Optional)",
    "ai.submit": "Get AI Recommendations",
    "ai.loading": "AI is analysing...",
    "ai.result.title": "AI Recommendations",
    "ai.loginRequired": "Please login to use AI recommendations",
    "ai.grades": "DSE Results",
    "ai.addSubject": "Add Subject",
    "ai.selectSubject": "Select Subject",
    "ai.generate": "Get AI Recommendations",
    "ai.result": "AI Recommendations",
    "ai.result.empty": "Fill in your results and AI will generate personalised recommendations",
    "ai.analyzing": "AI is analysing, please wait...",
    "ai.browseCourses": "Browse Related Courses",
    "ai.preferences": "Other Preferences (Optional)",
    "ai.preferences.placeholder": "e.g. Prefer Hong Kong Island campus, prefer less maths...",
    "ai.targetInstitutions.placeholder": "e.g. HKU, CUHK",
    "compare.title": "Course Comparison",
    "compare.subtitle": "Select 2-6 courses to compare",
    "compare.empty": "No courses selected",
    "compare.generate": "Generate Report",
    "compare.generatePDF": "Download PDF Report",
    "compare.saving": "Generating...",
    "compare.loginRequired": "Please login to save reports",
    "compare.analysis": "AI Analysis",
    "compare.analyze": "AI Deep Analysis",
    "compare.aiAnalysis": "AI Comparison Analysis",
    "compare.aiAnalysis.empty": "Click \"AI Deep Analysis\" to get an in-depth comparison of the selected courses",
    "admin.title": "Admin Panel",
    "admin.courses": "Course Management",
    "admin.addCourse": "Add Course",
    "admin.editCourse": "Edit Course",
    "admin.deleteCourse": "Delete Course",
    "admin.bulkImport": "Bulk Import",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.confirm.delete": "Confirm delete this course?",
    "admin.import.instructions": "Please upload course data in JSON format",
    "admin.import.success": "Successfully imported {count} courses",
    "qual.bachelor": "Bachelor's Degree",
    "qual.higher_diploma": "Higher Diploma",
    "qual.associate_degree": "Associate Degree",
    "funding.ugc": "UGC-funded",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
    "funding.self_financed": "Self-financed",
    // Interview
    "interview.required": "Interview Required",
    "interview.not_required": "No Interview",
    "interview.by_invitation": "By Invitation",
    "interview.portfolio": "Portfolio Interview",
    "scoreGap.above_median": "Above Median",
    "scoreGap.above_q1": "Above Lower Quartile",
    "scoreGap.below_q1": "Below Lower Quartile",
    "scoreGap.between_median_q1": "Between Median and Lower Quartile",
    "duration.years": "{n} years",
    "common.all": "All",
    "common.yes": "Yes",
    "common.no": "No",
    "common.unknown": "Unknown",
    "common.hkd": "HKD",
    "common.perYear": "/yr",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.retry": "Retry",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.reset": "Reset",
    "common.submit": "Submit",
    "common.loginRequired": "Please login first",
    "common.comingSoon": "Coming Soon",
    "common.page": "Page {page}",
    "common.of": "of",
    "common.results": "results",
    "common.noData": "No data available",
    "common.points": "pts",
    "footer.disclaimer": "This is a third-party information platform. All data is for reference only. Please refer to official university announcements.",
    "footer.copyright": "© 2025 JupaSearch. All rights reserved.",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("jupasearch-lang");
    return (saved as Language) || "zh-TW";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("jupasearch-lang", lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const text = translations[language][key] ?? translations["zh-TW"][key] ?? key;
    if (!params) return text;
    return Object.entries(params).reduce(
      (str, [k, v]) => str.replace(`{${k}}`, String(v)),
      text
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
