import { createContext, useContext, useState } from "react";

export type Language = "zh-TW" | "zh-CN" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  getInstitutionName: (code: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "zh-TW",
  setLanguage: () => {},
  t: (key) => key,
  getInstitutionName: (code) => code,
});

// ─── Institution name maps ────────────────────────────────────────────────────
export const INSTITUTION_NAMES: Record<string, Record<Language, string>> = {
  CityU: { "zh-TW": "香港城市大學", "zh-CN": "香港城市大学", en: "City University of Hong Kong" },
  HKBU: { "zh-TW": "香港浸會大學", "zh-CN": "香港浸会大学", en: "Hong Kong Baptist University" },
  LU: { "zh-TW": "嶺南大學", "zh-CN": "岭南大学", en: "Lingnan University" },
  CUHK: { "zh-TW": "香港中文大學", "zh-CN": "香港中文大学", en: "The Chinese University of Hong Kong" },
  EdUHK: { "zh-TW": "香港教育大學", "zh-CN": "香港教育大学", en: "The Education University of Hong Kong" },
  PolyU: { "zh-TW": "香港理工大學", "zh-CN": "香港理工大学", en: "The Hong Kong Polytechnic University" },
  HKUST: { "zh-TW": "香港科技大學", "zh-CN": "香港科技大学", en: "The Hong Kong University of Science and Technology" },
  HKU: { "zh-TW": "香港大學", "zh-CN": "香港大学", en: "The University of Hong Kong" },
  OUHK: { "zh-TW": "香港都會大學", "zh-CN": "香港都会大学", en: "Hong Kong Metropolitan University" },
  CHC: { "zh-TW": "港珠海學院", "zh-CN": "港珠海学院", en: "Chu Hai College of Higher Education" },
  HSUHK: { "zh-TW": "香港恒生大學", "zh-CN": "香港恒生大学", en: "Hang Seng University of Hong Kong" },
  HKMU: { "zh-TW": "香港都會大學", "zh-CN": "香港都会大学", en: "Hong Kong Metropolitan University" },
  SFU: { "zh-TW": "聖方濟各大學", "zh-CN": "圣方济各大学", en: "Saint Francis University" },
  THEi: { "zh-TW": "職業訓練局 – 香港高等教育科技學院", "zh-CN": "职业训练局 – 香港高等教育科技学院", en: "Vocational Training Council – Hong Kong Institute of Technology" },
  TWC: { "zh-TW": "東華學院", "zh-CN": "东华学院", en: "Tung Wah College" },
  UOWCHK: { "zh-TW": "香港伍倫貢學院", "zh-CN": "香港伍伦贡学院", en: "UOW College Hong Kong" },
  SHUE: { "zh-TW": "香港樹仁大學", "zh-CN": "香港树仁大学", en: "Shue Yan University" },
};

// Full Chinese name → code mapping for lookup
const INSTITUTION_FULL_NAME_MAP: Record<string, string> = {
  "香港城市大學": "CityU",
  "香港浸會大學": "HKBU",
  "嶺南大學": "LU",
  "香港中文大學": "CUHK",
  "香港教育大學": "EdUHK",
  "香港理工大學": "PolyU",
  "香港科技大學": "HKUST",
  "香港大學": "HKU",
  "香港都會大學": "OUHK",
  "港珠海學院": "CHC",
  "香港恒生大學": "HSUHK",
  "聖方濟各大學": "SFU",
  "職業訓練局 – 香港高等教育科技學院": "THEi",
  "東華學院": "TWC",
  "香港伍倫貢學院": "UOWCHK",
  "香港樹仁大學": "SHUE",
};

// ─── Degree type name maps ────────────────────────────────────────────────────
export const DEGREE_TYPE_NAMES: Record<string, Record<Language, string>> = {
  BA: { "zh-TW": "BA 文學士", "zh-CN": "BA 文学士", en: "BA – Bachelor of Arts" },
  BSc: { "zh-TW": "BSc 理學士", "zh-CN": "BSc 理学士", en: "BSc – Bachelor of Science" },
  BEng: { "zh-TW": "BEng 工程學士", "zh-CN": "BEng 工程学士", en: "BEng – Bachelor of Engineering" },
  BEd: { "zh-TW": "BEd 教育學士", "zh-CN": "BEd 教育学士", en: "BEd – Bachelor of Education" },
  LLB: { "zh-TW": "LLB 法學士", "zh-CN": "LLB 法学士", en: "LLB – Bachelor of Laws" },
  BBA: { "zh-TW": "BBA 工商管理學士", "zh-CN": "BBA 工商管理学士", en: "BBA – Bachelor of Business Administration" },
  BNurs: { "zh-TW": "BNurs 護理學士", "zh-CN": "BNurs 护理学士", en: "BNurs – Bachelor of Nursing" },
  BPharm: { "zh-TW": "BPharm 藥學士", "zh-CN": "BPharm 药学士", en: "BPharm – Bachelor of Pharmacy" },
  MBBS: { "zh-TW": "MBBS 醫學士", "zh-CN": "MBBS 医学士", en: "MBBS – Bachelor of Medicine and Surgery" },
  BDS: { "zh-TW": "BDS 牙醫學士", "zh-CN": "BDS 牙医学士", en: "BDS – Bachelor of Dental Surgery" },
  BSocSc: { "zh-TW": "BSocSc 社會科學學士", "zh-CN": "BSocSc 社会科学学士", en: "BSocSc – Bachelor of Social Sciences" },
  BSSc: { "zh-TW": "BSSc 社會科學學士", "zh-CN": "BSSc 社会科学学士", en: "BSSc – Bachelor of Social Sciences" },
  BFin: { "zh-TW": "BFin 金融學士", "zh-CN": "BFin 金融学士", en: "BFin – Bachelor of Finance" },
  BArch: { "zh-TW": "BArch 建築學士", "zh-CN": "BArch 建筑学士", en: "BArch – Bachelor of Architecture" },
  HD: { "zh-TW": "HD 高級文憑", "zh-CN": "HD 高级文凭", en: "HD – Higher Diploma" },
  AD: { "zh-TW": "AD 副學士", "zh-CN": "AD 副学士", en: "AD – Associate Degree" },
};

// ─── Translations ─────────────────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  "zh-TW": {
    // Nav
    "nav.home": "首頁",
    "nav.courses": "課程搜尋",
    "nav.favorites": "收藏課程",
    "nav.choices": "模擬志願",
    "nav.dse": "文憑試成績",
    "nav.ai": "AI 推薦",
    "nav.compare": "課程比較",
    "nav.admin": "管理後台",
    "nav.login": "登入",
    "nav.logout": "登出",
    "nav.profile": "我的帳戶",

    // Home
    "home.hero.title": "香港升學課程資訊平台",
    "home.hero.subtitle": "全面收錄 JUPAS 課程資訊，助你作出最佳升學選擇",
    "home.hero.cta": "立即搜尋課程",
    "home.hero.cta2": "文憑試成績輸入",
    "home.features.search": "智能搜尋",
    "home.features.search.desc": "多維度篩選，快速找到最適合的課程",
    "home.features.compare": "課程比較",
    "home.features.compare.desc": "並排比較多個課程，生成 PDF 報告",
    "home.features.dse": "文憑試成績",
    "home.features.dse.desc": "輸入 DSE 成績，即時計算各課程錄取可能性",
    "home.features.choices": "志願模擬",
    "home.features.choices.desc": "模擬填寫 20 個 JUPAS 志願",
    "home.stats.courses": "收錄課程",
    "home.stats.institutions": "收錄院校",
    "home.stats.users": "訪問次數",
    "home.modules.jupas": "JUPAS 課程",
    "home.modules.eapp": "E-APP 課程",
    "home.modules.eapp.soon": "即將推出",
    "home.modules.mainland": "內地升學",
    "home.modules.mainland.soon": "即將推出",

    // Courses
    "courses.title": "JUPAS 課程搜尋",
    "courses.search.placeholder": "搜尋課程名稱或課程代號...",
    "courses.filter.degreeType": "學位類型",
    "courses.filter.institution": "院校",
    "courses.filter.duration": "修讀年期",
    "courses.filter.qualification": "資歷架構",
    "courses.filter.scoring": "計分方式",
    "courses.filter.interview": "面試安排",
    "courses.filter.scoreGap": "分差",
    "courses.filter.funding": "資助類型",
    "courses.filter.groupA": "僅限組別A錄取",
    "courses.filter.tuition": "學費範圍",
    "courses.filter.tuition.unit": "元/年",
    "courses.filter.multipleSittings": "接受多次文憑試",
    "courses.filter.appliedLearning": "接受應用學習",
    "courses.filter.otherLanguage": "接受其他語言",
    "courses.sort.label": "排序方式",
    "courses.sort.quota_desc": "學額：多至少",
    "courses.sort.quota_asc": "學額：少至多",
    "courses.sort.tuition_desc": "學費：多至少",
    "courses.sort.tuition_asc": "學費：少至多",
    "courses.sort.probability_desc": "最可能取錄",
    "courses.sort.probability_asc": "最不可能取錄",
    "courses.sort.groupA_desc": "組別A申請者：多至少",
    "courses.sort.groupA_asc": "組別A申請者：少至多",
    "courses.sort.applicants_desc": "申請者：多至少",
    "courses.sort.applicants_asc": "申請者：少至多",
    "courses.col.code": "課程代號",
    "courses.col.name": "課程名稱",
    "courses.col.institution": "院校",
    "courses.col.quota": "收生人數",
    "courses.col.median": "去年加成後中位數",
    "courses.col.q1": "去年加成後下四分位數",
    "courses.col.minReq": "最低要求",
    "courses.col.tuition": "學費",
    "courses.col.duration": "修讀年期",
    "courses.col.scoring": "計分",
    "courses.col.admitted": "去年取錄人數",
    "courses.col.groupA": "去年組別A取錄人數",
    "courses.col.totalApplicants": "去年總申請人數",
    "courses.col.groupAApplicants": "去年組別A申請人數",
    "courses.noResults": "沒有符合條件的課程",
    "courses.loading": "載入中...",
    "courses.total": "共 {count} 個課程",
    "courses.clearFilters": "清除篩選",
    "courses.addToChoices": "加入志願",
    "courses.addToFavorites": "收藏",
    "courses.removeFromFavorites": "取消收藏",
    "courses.addToCompare": "加入比較",
    "courses.viewDetail": "查看詳情",
    "courses.new": "新課程",
    "courses.scoringChanged": "計分改變",
    "courses.groupAOnly": "是",

    // Detail
    "detail.back": "返回課程列表",
    "detail.basicInfo": "基本資料",
    "detail.admissionStats": "收生統計",
    "detail.requirements": "入學要求",
    "detail.description": "課程簡介",
    "detail.careers": "就業前景",
    "detail.requiredSubjects": "必修科目",
    "detail.weightedSubjects": "加成科目及倍率",
    "detail.interviewReq": "面試要求",
    "detail.website": "院校官方網站",
    "detail.jupasUrl": "JUPAS 官方網站",
    "detail.notFound": "找不到此課程",
    "detail.quota": "收生人數",
    "detail.median": "去年加成後中位數/平均數",
    "detail.q1": "去年加成後下四分位數",
    "detail.admitted": "去年取錄人數",
    "detail.groupAAdmitted": "去年組別A取錄人數",
    "detail.totalApplicants": "去年總申請人數",
    "detail.groupAApplicants": "去年組別A申請人數",
    "detail.minReq": "最低入學要求",
    "detail.scoringMethod": "計分方式",
    "detail.fundingType": "資助類型",
    "detail.duration": "修讀年期",
    "detail.tuition": "學費",
    "detail.qualification": "資歷架構",
    "detail.degreeType": "學位類型",
    "detail.jupasCode": "JUPAS 課程代號",
    "detail.institution": "院校",
    "detail.isNew": "新課程",
    "detail.scoringChanged": "計分方式改變",
    "detail.groupAOnly": "去年只錄取組別A",
    "detail.acceptAppliedLearning": "接受應用學習科目",
    "detail.acceptOtherLanguage": "接受其他語言科目",
    "detail.acceptMultipleSittings": "接受多次文憑試成績",

    // Favorites
    "favorites.title": "收藏課程",
    "favorites.empty": "你還未收藏任何課程",
    "favorites.empty.cta": "前往搜尋課程",
    "favorites.loginRequired": "登入後可永久儲存收藏",
    "favorites.localNote": "目前以本機儲存，登入後可同步至帳戶",

    // Choices
    "choices.title": "模擬填寫 JUPAS 志願",
    "choices.subtitle": "最多可選擇 20 個志願，拖動調整排序",
    "choices.empty": "尚未加入任何志願",
    "choices.empty.cta": "前往搜尋課程",
    "choices.loginRequired": "登入後可同步儲存志願",
    "choices.save": "儲存志願",
    "choices.saved": "志願已儲存",
    "choices.rank": "志願 {rank}",
    "choices.remove": "移除",
    "choices.max": "已達上限（20個志願）",
    "choices.addFromSearch": "從課程搜尋加入",

    // DSE Scores
    "dse.title": "文憑試成績",
    "dse.subtitle": "輸入您的文憑試成績，系統將自動儲存至本機，無需登入即可使用課程搜尋功能。",

    // AI
    "ai.title": "AI 課程推薦",
    "ai.subtitle": "輸入你的 DSE 成績，AI 為你推薦最適合的課程",

    // Compare
    "compare.title": "課程比較",
    "compare.subtitle": "選擇 2-6 個課程進行比較",
    "compare.empty": "尚未選擇任何課程",
    "compare.generate": "生成比較報告",
    "compare.generatePDF": "下載 PDF 報告",
    "compare.saving": "生成中...",
    "compare.loginRequired": "請登入以儲存報告",
    "compare.analysis": "比較分析",
    "compare.analyze": "深度分析",
    "compare.aiAnalysis": "比較分析",
    "compare.aiAnalysis.empty": "選擇課程後點擊「生成比較報告」",

    // Admin
    "admin.title": "管理後台",
    "admin.courses": "課程管理",
    "admin.addCourse": "新增課程",
    "admin.editCourse": "編輯課程",
    "admin.deleteCourse": "刪除課程",
    "admin.bulkImport": "批量匯入",
    "admin.save": "儲存",
    "admin.cancel": "取消",
    "admin.confirm.delete": "確認刪除此課程？",
    "admin.import.instructions": "請上傳 JSON 格式的課程資料",
    "admin.import.success": "成功匯入 {count} 個課程",

    // Qualification
    "qual.bachelor": "學士學位",
    "qual.higher_diploma": "高級文憑",
    "qual.associate_degree": "副學士",

    // Funding
    "funding.ugc": "教資會資助",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
    "funding.self_financed": "自資",

    // Interview (updated per requirement #29)
    "interview.yes_all": "有（所有申請人）",
    "interview.yes_selective": "有（按選擇性基準）",
    "interview.may_require": "可能需要面試及/或測試",
    "interview.special_cases": "僅特殊情況需要",
    "interview.no": "無面試",
    // Legacy keys (keep for backward compat)
    "interview.all_applicants": "有（所有申請者）",
    "interview.selective_basis": "有（選擇性）",
    "interview.no_interview": "無面試",
    "interview.required": "必須面試（所有申請者）",
    "interview.not_required": "無需面試",
    "interview.by_invitation": "獲邀面試",
    "interview.portfolio": "作品集面試",

    // Score gap
    "scoreGap.above_median": "高於中位數/平均數",
    "scoreGap.above_q1": "高於下四分位數",
    "scoreGap.below_q1": "低於下四分位數",
    "scoreGap.between_median_q1": "介乎中位數/平均數與下四分位數",

    // Multiple sittings
    "sittings.yes_no_penalty": "接受（不扣分）",
    "sittings.yes_with_penalty": "接受（有扣分）",
    "sittings.no": "不接受",

    // Duration
    "duration.years": "{n} 年",

    // Common
    "common.all": "全部",
    "common.yes": "是",
    "common.no": "否",
    "common.unknown": "未知",
    "common.hkd": "港幣",
    "common.perYear": "/年",
    "common.loading": "載入中...",
    "common.error": "發生錯誤",
    "common.retry": "重試",
    "common.close": "關閉",
    "common.confirm": "確認",
    "common.cancel": "取消",
    "common.save": "儲存",
    "common.edit": "編輯",
    "common.delete": "刪除",
    "common.search": "搜尋",
    "common.filter": "篩選",
    "common.sort": "排序",
    "common.reset": "重設",
    "common.submit": "提交",
    "common.loginRequired": "請先登入",
    "common.comingSoon": "即將推出",
    "common.page": "第 {page} 頁",
    "common.of": "共",
    "common.results": "個結果",
    "common.noData": "暫無資料",
    "common.points": "分",

    // Footer
    "footer.disclaimer": "本平台為第三方資訊平台，所有資料僅供參考，請以各院校官方公佈為準。",
    "footer.copyright": "© 2026 JupaSearch. 版權所有。",
  },

  "zh-CN": {
    "nav.home": "首页",
    "nav.courses": "课程搜索",
    "nav.favorites": "收藏课程",
    "nav.choices": "模拟志愿",
    "nav.dse": "文凭试成绩",
    "nav.ai": "AI 推荐",
    "nav.compare": "课程比较",
    "nav.admin": "管理后台",
    "nav.login": "登录",
    "nav.logout": "登出",
    "nav.profile": "我的账户",
    "home.hero.title": "香港升学课程信息平台",
    "home.hero.subtitle": "全面收录 JUPAS 课程信息，助你作出最佳升学选择",
    "home.hero.cta": "立即搜索课程",
    "home.hero.cta2": "文凭试成绩输入",
    "home.features.search": "智能搜索",
    "home.features.search.desc": "多维度筛选，快速找到最适合的课程",
    "home.features.compare": "课程比较",
    "home.features.compare.desc": "并排比较多个课程，生成 PDF 报告",
    "home.features.dse": "文凭试成绩",
    "home.features.dse.desc": "输入 DSE 成绩，即时计算各课程录取可能性",
    "home.features.choices": "志愿模拟",
    "home.features.choices.desc": "模拟填写 20 个 JUPAS 志愿",
    "home.stats.courses": "收录课程",
    "home.stats.institutions": "收录院校",
    "home.stats.users": "访问次数",
    "home.modules.jupas": "JUPAS 课程",
    "home.modules.eapp": "E-APP 课程",
    "home.modules.eapp.soon": "即将推出",
    "home.modules.mainland": "内地升学",
    "home.modules.mainland.soon": "即将推出",
    "courses.title": "JUPAS 课程搜索",
    "courses.search.placeholder": "搜索课程名称或课程代号...",
    "courses.filter.degreeType": "学位类型",
    "courses.filter.institution": "院校",
    "courses.filter.duration": "修读年期",
    "courses.filter.qualification": "资历架构",
    "courses.filter.scoring": "计分方式",
    "courses.filter.interview": "面试安排",
    "courses.filter.scoreGap": "分差",
    "courses.filter.funding": "资助类型",
    "courses.filter.groupA": "仅限组别A录取",
    "courses.filter.tuition": "学费范围",
    "courses.filter.tuition.unit": "元/年",
    "courses.filter.multipleSittings": "接受多次文凭试",
    "courses.filter.appliedLearning": "接受应用学习",
    "courses.filter.otherLanguage": "接受其他语言",
    "courses.sort.label": "排序方式",
    "courses.sort.quota_desc": "学额：多至少",
    "courses.sort.quota_asc": "学额：少至多",
    "courses.sort.tuition_desc": "学费：多至少",
    "courses.sort.tuition_asc": "学费：少至多",
    "courses.sort.probability_desc": "最可能录取",
    "courses.sort.probability_asc": "最不可能录取",
    "courses.sort.groupA_desc": "组别A申请者：多至少",
    "courses.sort.groupA_asc": "组别A申请者：少至多",
    "courses.sort.applicants_desc": "申请者：多至少",
    "courses.sort.applicants_asc": "申请者：少至多",
    "courses.col.code": "课程代号",
    "courses.col.name": "课程名称",
    "courses.col.institution": "院校",
    "courses.col.quota": "收生人数",
    "courses.col.median": "去年加成后中位数",
    "courses.col.q1": "去年加成后下四分位数",
    "courses.col.minReq": "最低要求",
    "courses.col.tuition": "学费",
    "courses.col.duration": "修读年期",
    "courses.col.scoring": "计分",
    "courses.col.admitted": "去年录取人数",
    "courses.col.groupA": "去年组别A录取人数",
    "courses.col.totalApplicants": "去年总申请人数",
    "courses.col.groupAApplicants": "去年组别A申请人数",
    "courses.noResults": "没有符合条件的课程",
    "courses.loading": "加载中...",
    "courses.total": "共 {count} 个课程",
    "courses.clearFilters": "清除筛选",
    "courses.addToChoices": "加入志愿",
    "courses.addToFavorites": "收藏",
    "courses.removeFromFavorites": "取消收藏",
    "courses.addToCompare": "加入比较",
    "courses.viewDetail": "查看详情",
    "courses.new": "新课程",
    "courses.scoringChanged": "计分改变",
    "courses.groupAOnly": "是",
    "detail.back": "返回课程列表",
    "detail.basicInfo": "基本资料",
    "detail.admissionStats": "收生统计",
    "detail.requirements": "入学要求",
    "detail.description": "课程简介",
    "detail.careers": "就业前景",
    "detail.requiredSubjects": "必修科目",
    "detail.weightedSubjects": "加成科目及倍率",
    "detail.interviewReq": "面试要求",
    "detail.website": "院校官方网站",
    "detail.jupasUrl": "JUPAS 官方网站",
    "detail.notFound": "找不到此课程",
    "detail.quota": "收生人数",
    "detail.median": "去年加成后中位数/平均数",
    "detail.q1": "去年加成后下四分位数",
    "detail.admitted": "去年录取人数",
    "detail.groupAAdmitted": "去年组别A录取人数",
    "detail.totalApplicants": "去年总申请人数",
    "detail.groupAApplicants": "去年组别A申请人数",
    "detail.minReq": "最低入学要求",
    "detail.scoringMethod": "计分方式",
    "detail.fundingType": "资助类型",
    "detail.duration": "修读年期",
    "detail.tuition": "学费",
    "detail.qualification": "资历架构",
    "detail.degreeType": "学位类型",
    "detail.jupasCode": "JUPAS 课程代号",
    "detail.institution": "院校",
    "detail.isNew": "新课程",
    "detail.scoringChanged": "计分方式改变",
    "detail.groupAOnly": "去年只录取组别A",
    "detail.acceptAppliedLearning": "接受应用学习科目",
    "detail.acceptOtherLanguage": "接受其他语言科目",
    "detail.acceptMultipleSittings": "接受多次文凭试成绩",
    "favorites.title": "收藏课程",
    "favorites.empty": "你还未收藏任何课程",
    "favorites.empty.cta": "前往搜索课程",
    "favorites.loginRequired": "登录后可永久保存收藏",
    "favorites.localNote": "目前以本机保存，登录后可同步至账户",
    "choices.title": "模拟填写 JUPAS 志愿",
    "choices.subtitle": "最多可选择 20 个志愿，拖动调整排序",
    "choices.empty": "尚未加入任何志愿",
    "choices.empty.cta": "前往搜索课程",
    "choices.loginRequired": "登录后可同步保存志愿",
    "choices.save": "保存志愿",
    "choices.saved": "志愿已保存",
    "choices.rank": "志愿 {rank}",
    "choices.remove": "移除",
    "choices.max": "已达上限（20个志愿）",
    "choices.addFromSearch": "从课程搜索加入",
    "dse.title": "文凭试成绩",
    "dse.subtitle": "输入您的文凭试成绩，系统将自动保存至本机，无需登录即可使用课程搜尋功能。",
    "ai.title": "AI 课程推荐",
    "ai.subtitle": "输入你的 DSE 成绩，AI 为你推荐最适合的课程",
    "compare.title": "课程比较",
    "compare.subtitle": "选择 2-6 个课程进行比较",
    "compare.empty": "尚未选择任何课程",
    "compare.generate": "生成比较报告",
    "compare.generatePDF": "下载 PDF 报告",
    "compare.saving": "生成中...",
    "compare.loginRequired": "请登录以保存报告",
    "compare.analysis": "比较分析",
    "compare.analyze": "深度分析",
    "compare.aiAnalysis": "比较分析",
    "compare.aiAnalysis.empty": "选择课程后点击「生成比较报告」",
    "admin.title": "管理后台",
    "admin.courses": "课程管理",
    "admin.addCourse": "新增课程",
    "admin.editCourse": "编辑课程",
    "admin.deleteCourse": "删除课程",
    "admin.bulkImport": "批量导入",
    "admin.save": "保存",
    "admin.cancel": "取消",
    "admin.confirm.delete": "确认删除此课程？",
    "admin.import.instructions": "请上传 JSON 格式的课程资料",
    "admin.import.success": "成功导入 {count} 个课程",
    "qual.bachelor": "学士学位",
    "qual.higher_diploma": "高级文凭",
    "qual.associate_degree": "副学士",
    "funding.ugc": "教资会资助",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
    "funding.self_financed": "自资",
    "interview.yes_all": "有（所有申请人）",
    "interview.yes_selective": "有（按选择性基准）",
    "interview.may_require": "可能需要面试及/或测试",
    "interview.special_cases": "仅特殊情况需要",
    "interview.no": "无面试",
    // Legacy keys (keep for backward compat)
    "interview.all_applicants": "有（所有申请者）",
    "interview.selective_basis": "有（选择性）",
    "interview.no_interview": "无面试",
    "interview.required": "必须面试（所有申请人）",
    "interview.not_required": "无需面试",
    "interview.by_invitation": "获邀面试",
    "interview.portfolio": "作品集面试",
    "scoreGap.above_median": "高于中位数/平均数",
    "scoreGap.above_q1": "高于下四分位数",
    "scoreGap.below_q1": "低于下四分位数",
    "scoreGap.between_median_q1": "介于中位数/平均数与下四分位数",
    "sittings.yes_no_penalty": "接受（不扣分）",
    "sittings.yes_with_penalty": "接受（有扣分）",
    "sittings.no": "不接受",
    "duration.years": "{n} 年",
    "common.all": "全部",
    "common.yes": "是",
    "common.no": "否",
    "common.unknown": "未知",
    "common.hkd": "港币",
    "common.perYear": "/年",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.retry": "重试",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.reset": "重设",
    "common.submit": "提交",
    "common.loginRequired": "请先登录",
    "common.comingSoon": "即将推出",
    "common.page": "第 {page} 页",
    "common.of": "共",
    "common.results": "个结果",
    "common.noData": "暂无资料",
    "common.points": "分",
    "footer.disclaimer": "本平台为第三方信息平台，所有资料仅供参考，请以各院校官方公布为准。",
    "footer.copyright": "© 2026 JupaSearch. 版权所有。",
  },

  en: {
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.favorites": "Favourites",
    "nav.choices": "My Choices",
    "nav.dse": "DSE Scores",
    "nav.ai": "AI Advisor",
    "nav.compare": "Compare",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.profile": "My Account",
    "home.hero.title": "Hong Kong University Admissions Platform",
    "home.hero.subtitle": "Comprehensive JUPAS course information to help you make the best choice",
    "home.hero.cta": "Search Courses",
    "home.hero.cta2": "Enter DSE Scores",
    "home.features.search": "Smart Search",
    "home.features.search.desc": "Multi-dimensional filters to find the perfect course",
    "home.features.compare": "Course Comparison",
    "home.features.compare.desc": "Compare courses side by side and generate PDF reports",
    "home.features.dse": "DSE Scores",
    "home.features.dse.desc": "Enter DSE results to instantly calculate admission chances",
    "home.features.choices": "Choice Simulation",
    "home.features.choices.desc": "Simulate filling in 20 JUPAS choices",
    "home.stats.courses": "Courses Listed",
    "home.stats.institutions": "Institutions",
    "home.stats.users": "Page Views",
    "home.modules.jupas": "JUPAS Courses",
    "home.modules.eapp": "E-APP Courses",
    "home.modules.eapp.soon": "Coming Soon",
    "home.modules.mainland": "Mainland Studies",
    "home.modules.mainland.soon": "Coming Soon",
    "courses.title": "JUPAS Course Search",
    "courses.search.placeholder": "Search by course name or code...",
    "courses.filter.degreeType": "Degree Type",
    "courses.filter.institution": "Institution",
    "courses.filter.duration": "Duration",
    "courses.filter.qualification": "Qualification",
    "courses.filter.scoring": "Scoring Method",
    "courses.filter.interview": "Interview",
    "courses.filter.scoreGap": "Score Gap",
    "courses.filter.funding": "Funding Type",
    "courses.filter.groupA": "Band A Admission Only",
    "courses.filter.tuition": "Tuition Range",
    "courses.filter.tuition.unit": "HKD/yr",
    "courses.filter.multipleSittings": "Accepts Multiple Sittings",
    "courses.filter.appliedLearning": "Accepts Applied Learning",
    "courses.filter.otherLanguage": "Accepts Other Languages",
    "courses.sort.label": "Sort By",
    "courses.sort.quota_desc": "Quota: High to Low",
    "courses.sort.quota_asc": "Quota: Low to High",
    "courses.sort.tuition_desc": "Tuition: High to Low",
    "courses.sort.tuition_asc": "Tuition: Low to High",
    "courses.sort.probability_desc": "Most Likely to Admit",
    "courses.sort.probability_asc": "Least Likely to Admit",
    "courses.sort.groupA_desc": "Group A Applicants: High to Low",
    "courses.sort.groupA_asc": "Group A Applicants: Low to High",
    "courses.sort.applicants_desc": "Applicants: High to Low",
    "courses.sort.applicants_asc": "Applicants: Low to High",
    "courses.col.code": "Code",
    "courses.col.name": "Course Name",
    "courses.col.institution": "Institution",
    "courses.col.quota": "Quota",
    "courses.col.median": "Last Year Median (Weighted)",
    "courses.col.q1": "Last Year Lower Quartile (Weighted)",
    "courses.col.minReq": "Min. Req.",
    "courses.col.tuition": "Tuition",
    "courses.col.duration": "Duration",
    "courses.col.scoring": "Scoring",
    "courses.col.admitted": "Last Year Admitted",
    "courses.col.groupA": "Last Year Group A Admitted",
    "courses.col.totalApplicants": "Last Year Total Applicants",
    "courses.col.groupAApplicants": "Last Year Group A Applicants",
    "courses.noResults": "No courses found",
    "courses.loading": "Loading...",
    "courses.total": "{count} courses found",
    "courses.clearFilters": "Clear Filters",
    "courses.addToChoices": "Add to Choices",
    "courses.addToFavorites": "Favourite",
    "courses.removeFromFavorites": "Unfavourite",
    "courses.addToCompare": "Compare",
    "courses.viewDetail": "View Details",
    "courses.new": "New",
    "courses.scoringChanged": "Scoring Changed",
    "courses.groupAOnly": "Yes",
    "detail.back": "Back to Course List",
    "detail.basicInfo": "Basic Information",
    "detail.admissionStats": "Admission Statistics",
    "detail.requirements": "Entry Requirements",
    "detail.description": "Course Description",
    "detail.careers": "Career Prospects",
    "detail.requiredSubjects": "Required Subjects",
    "detail.weightedSubjects": "Weighted Subjects & Multipliers",
    "detail.interviewReq": "Interview Requirements",
    "detail.website": "University Website",
    "detail.jupasUrl": "JUPAS Website",
    "detail.notFound": "Course not found",
    "detail.quota": "Quota",
    "detail.median": "Last Year Median/Mean (Weighted)",
    "detail.q1": "Last Year Lower Quartile (Weighted)",
    "detail.admitted": "Last Year Admitted",
    "detail.groupAAdmitted": "Last Year Group A Admitted",
    "detail.totalApplicants": "Last Year Total Applicants",
    "detail.groupAApplicants": "Last Year Group A Applicants",
    "detail.minReq": "Minimum Entry Requirement",
    "detail.scoringMethod": "Scoring Method",
    "detail.fundingType": "Funding Type",
    "detail.duration": "Duration",
    "detail.tuition": "Tuition Fee",
    "detail.qualification": "Qualification",
    "detail.degreeType": "Degree Type",
    "detail.jupasCode": "JUPAS Course Code",
    "detail.institution": "Institution",
    "detail.isNew": "New Course",
    "detail.scoringChanged": "Scoring Method Changed",
    "detail.groupAOnly": "Last Year Group A Only",
    "detail.acceptAppliedLearning": "Accepts Applied Learning",
    "detail.acceptOtherLanguage": "Accepts Other Languages",
    "detail.acceptMultipleSittings": "Accepts Multiple DSE Sittings",
    "favorites.title": "Favourite Courses",
    "favorites.empty": "You have no favourite courses yet",
    "favorites.empty.cta": "Browse Courses",
    "favorites.loginRequired": "Login to save favourites permanently",
    "favorites.localNote": "Currently saved locally. Login to sync to your account.",
    "choices.title": "JUPAS Choice Simulation",
    "choices.subtitle": "Select up to 20 choices and drag to reorder",
    "choices.empty": "No choices added yet",
    "choices.empty.cta": "Browse Courses",
    "choices.loginRequired": "Login to sync your choices",
    "choices.save": "Save Choices",
    "choices.saved": "Choices saved",
    "choices.rank": "Choice {rank}",
    "choices.remove": "Remove",
    "choices.max": "Maximum 20 choices reached",
    "choices.addFromSearch": "Add from Course Search",
    "dse.title": "DSE Scores",
    "dse.subtitle": "Enter your DSE scores. They are automatically saved locally without login, ready to use for course search.",
    "ai.title": "AI Course Advisor",
    "ai.subtitle": "Enter your DSE results and get personalised course recommendations",
    "compare.title": "Course Comparison",
    "compare.subtitle": "Select 2-6 courses to compare",
    "compare.empty": "No courses selected",
    "compare.generate": "Generate Report",
    "compare.generatePDF": "Download PDF Report",
    "compare.saving": "Generating...",
    "compare.loginRequired": "Please login to save reports",
    "compare.analysis": "Comparison Analysis",
    "compare.analyze": "Deep Analysis",
    "compare.aiAnalysis": "Comparison Analysis",
    "compare.aiAnalysis.empty": "Select courses and click Generate Report",
    "admin.title": "Admin Panel",
    "admin.courses": "Course Management",
    "admin.addCourse": "Add Course",
    "admin.editCourse": "Edit Course",
    "admin.deleteCourse": "Delete Course",
    "admin.bulkImport": "Bulk Import",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.confirm.delete": "Confirm delete this course?",
    "admin.import.instructions": "Please upload course data in JSON format",
    "admin.import.success": "Successfully imported {count} courses",
    "qual.bachelor": "Bachelor's Degree",
    "qual.higher_diploma": "Higher Diploma",
    "qual.associate_degree": "Associate Degree",
    "funding.ugc": "UGC-funded",
    "funding.nmtss": "NMTSS",
    "funding.sssdp": "SSSDP",
    "funding.self_financed": "Self-financed",
    "interview.yes_all": "Yes (for all applicants)",
    "interview.yes_selective": "Yes (on a selective basis)",
    "interview.may_require": "May require interview and/or test",
    "interview.special_cases": "For special cases only",
    "interview.no": "No",
    // Legacy keys (keep for backward compat)
    "interview.all_applicants": "Yes (for all applicants)",
    "interview.selective_basis": "Yes (on a selective basis)",
    "interview.no_interview": "No",
    "interview.required": "Interview Required (All)",
    "interview.not_required": "No Interview",
    "interview.by_invitation": "By Invitation",
    "interview.portfolio": "Portfolio Interview",
    "scoreGap.above_median": "Above Median/Mean",
    "scoreGap.above_q1": "Above Lower Quartile",
    "scoreGap.below_q1": "Below Lower Quartile",
    "scoreGap.between_median_q1": "Between Median/Mean and Lower Quartile",
    "sittings.yes_no_penalty": "Yes (No Penalty)",
    "sittings.yes_with_penalty": "Yes (With Penalty)",
    "sittings.no": "No",
    "duration.years": "{n} years",
    "common.all": "All",
    "common.yes": "Yes",
    "common.no": "No",
    "common.unknown": "Unknown",
    "common.hkd": "HKD",
    "common.perYear": "/yr",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.retry": "Retry",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.reset": "Reset",
    "common.submit": "Submit",
    "common.loginRequired": "Please login first",
    "common.comingSoon": "Coming Soon",
    "common.page": "Page {page}",
    "common.of": "of",
    "common.results": "results",
    "common.noData": "No data available",
    "common.points": "pts",
    "footer.disclaimer": "This is a third-party information platform. All data is for reference only. Please refer to official university announcements.",
    "footer.copyright": "© 2026 JupaSearch. All rights reserved.",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("jupasearch-lang");
    return (saved as Language) || "zh-TW";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("jupasearch-lang", lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const text = translations[language][key] ?? translations["zh-TW"][key] ?? key;
    if (!params) return text;
    return Object.entries(params).reduce(
      (str, [k, v]) => str.replace(`{${k}}`, String(v)),
      text
    );
  };

  // Resolve institution name from code or full Chinese name
  const getInstitutionName = (codeOrName: string): string => {
    // Try direct code lookup
    if (INSTITUTION_NAMES[codeOrName]) {
      return INSTITUTION_NAMES[codeOrName][language];
    }
    // Try full Chinese name → code lookup
    const code = INSTITUTION_FULL_NAME_MAP[codeOrName];
    if (code && INSTITUTION_NAMES[code]) {
      return INSTITUTION_NAMES[code][language];
    }
    // Fallback: return as-is
    return codeOrName;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getInstitutionName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
